import express from "express";
import { authenticate } from "../middleware/authenticate.js";
import adminCreateUserRoutes from "./createUser.js";
import signInUserRoutes from "./signInUsers.js";
import subjectsRoutes from "./subjects.js";
import academicRecordsRoutes from "./academicRecord.js";
import gradesUpdateRoutes from "./gradeUpdate.js";
import studentsGetRoutes from "./studentsGet.js";
import getStudentsSubjectRoutes from "./getStudentsSubject.js";
import { checkIfSignedIn } from "../controllers/checkIfSignedIn.js";
import { logoutController } from "../controllers/logoutController.js";
const router = express.Router();

router.use("/admin", authenticate, adminCreateUserRoutes);
router.use("/signin", signInUserRoutes);
router.use("/subjects",authenticate, subjectsRoutes);
router.use("/academicRecords",authenticate, academicRecordsRoutes);
router.use("/lecturer",authenticate, gradesUpdateRoutes);
router.use("/lecturer",authenticate, studentsGetRoutes);
router.use("/student",authenticate, getStudentsSubjectRoutes);
router.get("/auth/status", authenticate, checkIfSignedIn);
router.get("/logout", logoutController);
export default router;
